docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - export YT_SPLEETER_IMAGE="$CI_REGISTRY_IMAGE:latest"
    - docker build --pull -t "$YT_SPLEETER_IMAGE" .
    - docker push "$YT_SPLEETER_IMAGE"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
