name: Docker Image CI

on:
  push:
    branches: [ Installation ]
  pull_request:
    branches: [ Installation ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t zabeaty/spleeter .
